// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8MeRLR9iwRcYQ_YnwSBvrRg1OK9S4WU',
    appId: '1:279412283933:web:d63e75cba766e5b46204f4',
    messagingSenderId: '279412283933',
    projectId: 'proco-6c50c',
    authDomain: 'proco-6c50c.firebaseapp.com',
    databaseURL: 'https://proco-6c50c-default-rtdb.firebaseio.com',
    storageBucket: 'proco-6c50c.appspot.com',
    measurementId: 'G-2FZYLK3SES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsUp4CavY3Y1XshXXBHLnlUF2CWL6YHj8',
    appId: '1:279412283933:android:a36728332ec5b88c6204f4',
    messagingSenderId: '279412283933',
    projectId: 'proco-6c50c',
    databaseURL: 'https://proco-6c50c-default-rtdb.firebaseio.com',
    storageBucket: 'proco-6c50c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBhRG5riP5eDHPaujqj1tid6EWzLrBR2U',
    appId: '1:279412283933:ios:894f4c62b7555a736204f4',
    messagingSenderId: '279412283933',
    projectId: 'proco-6c50c',
    databaseURL: 'https://proco-6c50c-default-rtdb.firebaseio.com',
    storageBucket: 'proco-6c50c.appspot.com',
    iosBundleId: 'com.example.proco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBhRG5riP5eDHPaujqj1tid6EWzLrBR2U',
    appId: '1:279412283933:ios:3427bbbae98a05c06204f4',
    messagingSenderId: '279412283933',
    projectId: 'proco-6c50c',
    databaseURL: 'https://proco-6c50c-default-rtdb.firebaseio.com',
    storageBucket: 'proco-6c50c.appspot.com',
    iosBundleId: 'com.example.proco.RunnerTests',
  );
}
